### ISSUE TITLE
Katselmointi

### ISSUE THREAD

**Issue by Jakousa** [Ouzii/adhoctripper#1]
# Katselmointi

### Mitä tein

* 4.4.2019 klo ~18

* Käytin sovellusta kirjautumatta
  * Pyrin tarkastelemaan jaettuja reittejä
* Käytin sovellusta kirjauduttuani
  * Tarkastelin jaettuja reittejä
  * Lisäsin kaksi reittiä
  * Lisäsin yhden auton
  * Jaoin yhden reitin

### Kokemus

* App ei vaikuta toimivan jos käyttäjä ei ole ainakin kerran kirjautunut sisälle.
  * Repro: Avaa incognito välilehdellä jokin jaetuista reiteistä. Tai poista historiatiedot ja avaa PWA.
* Käyttäjä kirjautuu rekisteröinnin jälkeen automaattisesti, erittäin hyvä!
* En ole ihan varma miksi annoin sähköpostiosoitteen.
  * Kehitysidea: Mitä jos käyttäjänimi annetaan vasta kun käyttäjänimestä on hyötyä (esim. tulevaisuudessa reittejä jaettaessa?)
* Todella selkeäkäyttöinen. Kaikki olennaisimmat asiat on helposti saatavilla.
  * Selkeä mobile design isoilla napeilla
* Osa ominaisuuksista hieman piilossa.
  * Kehitysidea: Autoihin linkki myös reitin katselun luota.
* Autot eivät tule listaan heti luomisen jälkeen.
  * Repro: Tein matkan ja huomasin että voisin lisätä auton. Lisättyäni auton se ei tullut heti valikkoon vaan jouduin valitsemaan toisen matkan ja sitten alkuperäisen matkan että se ilmestyi listaan.
* Erinomainen README
* Alapalkkiin jäävät ilmoitukset ovat hieman vaikeassa paikassa huomata. Esimerkiksi ajoneuvon tallennuksessa.
* Pidän myös luettavista ajo-ohjeista. Niillä on tosin ongelmia asettua kunnolla pienelle näytölle.

## Backend

* Selkeästi nimetyt tiedostot. :thumbsup:
* Kansiorakennetta voisi siistiä siirtämällä koko backendin omaan kansioonsa.
* body-parserin sijaan on mahdollisuus käyttää: <https://expressjs.com/en/api.html>
* Suosittelen käyttämään eslintiä. :star:
* config tiedostossa voisit käyttää fallback arvoja esim `...PORT || 3000`.
* Sen sijaan että `let decoded = jwt.verify(request.headers.token, secret)` ja siihen liittyvät try catchit tehdään jokaisen kontrollerin alussa voisit tehdä oman middlewaren. <https://expressjs.com/en/guide/writing-middleware.html>. Jotakin tämän kaltaista ennen muita routeja:

```js
  app.use((request, response, next) => {
    try {
      let decoded = jwt.verify(request.headers.token, secret)
      ...
      next()
    } catch (err) {
      // Not authorized, try logging in
    }
  })
```

* Suosittelen myös routejen ja kontrollerien erottelua: routes tiedosto sisältää kaikki reitit esim `router.get('/account', accountController.getAccount)`. Ja itse käsittelevät funktiot sijaitsisivat controllereissa. Tällöin jokainen rajapinta olisi nähtävillä yhdestä tiedostosta.

## Frontend

* App.js on melko suuri ja monimutkainen tiedosto, kannattanee jakaa se pienempiin osiin.
* Importeissa kannattaa pitää tietty järjestys, ensin npm moduulit, sen jälkeen omat
  * esim nyt App.js tiedostossa on näin:

```js
import React, { Component } from 'react';
import './App.css';
import { connect } from 'react-redux'
import HeaderWithRouter from './components/Header';
import SwipeableRoutes from 'react-swipeable-routes';
import { Route } from 'react-router-dom';
```

kun kannattaa suosia tämmöistä järjestystä

```js
import React, { Component } from 'react';
import { connect } from 'react-redux'
import { Route } from 'react-router-dom';
import SwipeableRoutes from 'react-swipeable-routes';

import HeaderWithRouter from './components/Header';
import './App.css';

```

* Eslint esimerkiksi airbnb asetuksilla <https://www.npmjs.com/package/eslint-config-airbnb> olisi huomannut "ongelman". :star:
  * Laitan PR jossa airbnb asetukset. Et käyttänyt puolipisteitä joten poistin säännön käytöstä. Samoin .jsx loppu ja prop-types kirjastosta. Olisi hyvä jos ehdit katsoa käytänteitä tarkempien eslint sääntöjen kanssa.
* Voisimme poistaa luokkakomponentit kokonaan nyt kun hookit on tarjolla. Jotta pääset **reunalle** suosittelen lukemaan <https://reactjs.org/docs/hooks-intro.html> ja ottamaan **heti** käyttöön jotta kokemusta karttuu.

* Huomasin, että `ShowRoute` sisältää staten googleLink jota ei käytetä. 

* `await this.setState()` ei käy järkeen sillä setState ei palauta promisea. Se on kuitenkin asynkroninen joten suorituksesta ei ole mitään takeita. Jos haluat että sen jälkeen tapahtuu jotain niin käytä [callbackiä](https://medium.learnreact.com/setstate-takes-a-callback-1f71ad5d2296)

### Pieni esimerkki *ref*aktorointi

Refaktoroidaan hieman yhdessä. Otetaan käsittelyyn `GoogleMapLink`:

Ensisilmäyksellä vaikuttaa siltä että `state` on turha ja luettavuuttakin voisi parantaa.

Komponenttia käytetään kahdessa paikassa `ShowRoute` ja `Map`.

Luetaan <https://reactjs.org/docs/refs-and-the-dom.html> erityisesti kohdat `Don’t Overuse Refs`, `Avoid using refs for anything that can be done declaratively.` ja `take a moment and think more critically about where state should be owned in the component hierarchy.`

`GoogleMapLink` voitaisiin ottaa käyttöön passaamalla `googleLink` propsina. Tällöin ei updateLinkiä eikä komponentin statea tarvitse.

PS: Onkohan edes tarpeellista säilyttää googleLinkiä statessa alkuunkaan? Tehokkuus hyötyä siitä saadaan mutta `ennenaikainen optimointi on kaiken pahan alku ja juuri`. Nopeampi tapa refaktoroida voisikin olla passata koko markerit propsina GoogleMapLinkille ja tehdä renderissä ennen returnia linkin rakennus. Optimoinniksi voisi sitten myöhemmin palauttaa state ja ottaa linkki statesta jos markerit eivät ole muuttuneet. (hook maailman `useState` ja `useEffect` auttavat) Näin vastuu linkistä, sen rakennuksesta ja rakennuksen aloittamisesta olisi yhdessä paikassa.

## Kokonaisuus

Eslintin voisit ottaa käyttöön niin pienistä ongelmista pääsee eroon tehokkaasti. Prepush / precommit hookeilla (esim. <https://www.npmjs.com/package/husky>) saisit varmistettua että eslint ei unohdu.

Bugit toivottavasti korjaat pian. Muuten mitään moitittavaa ei ole. Tästä on hyvä jatkaa.

❤️ / 🌟

**Comment by Ouzii** [comment]
Bugit korjattu. Eipäs ollut hajuakaan, että tuommoiset hooksit tulleet. Kiitos vinkistä!
